const input = 'A Y\n' +
    'B X\n' +
    'C X\n' +
    'A Z\n' +
    'B Y\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'B Y\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'B Y\n' +
    'A Z\n' +
    'B X\n' +
    'C Z\n' +
    'C X\n' +
    'C X\n' +
    'B Y\n' +
    'C X\n' +
    'A X\n' +
    'B Y\n' +
    'B Z\n' +
    'A Z\n' +
    'B Y\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'B Y\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'B Y\n' +
    'C X\n' +
    'C X\n' +
    'B Y\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'A Y\n' +
    'B X\n' +
    'C X\n' +
    'B X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'C Z\n' +
    'C X\n' +
    'A Y\n' +
    'B Y\n' +
    'B Y\n' +
    'B X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Y\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'B Y\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'B Y\n' +
    'C X\n' +
    'B Y\n' +
    'A X\n' +
    'A Y\n' +
    'C Y\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'A X\n' +
    'A Z\n' +
    'A X\n' +
    'C X\n' +
    'C X\n' +
    'A X\n' +
    'C X\n' +
    'B Y\n' +
    'A Z\n' +
    'A Y\n' +
    'A Z\n' +
    'B X\n' +
    'C X\n' +
    'B X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'C Z\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'A X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'A Y\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'C Z\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'B Y\n' +
    'C X\n' +
    'C X\n' +
    'A Y\n' +
    'A Z\n' +
    'A Z\n' +
    'A Z\n' +
    'A Y\n' +
    'B Y\n' +
    'A Z\n' +
    'C X\n' +
    'A Y\n' +
    'A Z\n' +
    'A Y\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'B X\n' +
    'B Y\n' +
    'A Z\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'A X\n' +
    'B X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'A X\n' +
    'A Z\n' +
    'C Y\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'C Z\n' +
    'C X\n' +
    'A Z\n' +
    'A X\n' +
    'C Y\n' +
    'A X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A X\n' +
    'A X\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'A Z\n' +
    'A Z\n' +
    'A Z\n' +
    'A Y\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'A Z\n' +
    'B Y\n' +
    'C X\n' +
    'C X\n' +
    'A X\n' +
    'B X\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'A Y\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Y\n' +
    'C X\n' +
    'C Y\n' +
    'C Z\n' +
    'C X\n' +
    'C X\n' +
    'B Y\n' +
    'C X\n' +
    'A Z\n' +
    'C Z\n' +
    'A Z\n' +
    'C X\n' +
    'A Y\n' +
    'B Y\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'B X\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'B X\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'A X\n' +
    'B Y\n' +
    'C Y\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'A Z\n' +
    'B Y\n' +
    'B X\n' +
    'C X\n' +
    'A Z\n' +
    'A Y\n' +
    'B Z\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'A X\n' +
    'C X\n' +
    'A Z\n' +
    'B Y\n' +
    'A Z\n' +
    'C Z\n' +
    'B X\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Y\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'A X\n' +
    'C Z\n' +
    'A Y\n' +
    'C X\n' +
    'C X\n' +
    'A Y\n' +
    'A X\n' +
    'B Y\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'A X\n' +
    'C X\n' +
    'A X\n' +
    'A X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'A X\n' +
    'A Z\n' +
    'C X\n' +
    'B Y\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'A X\n' +
    'B X\n' +
    'C X\n' +
    'B Y\n' +
    'A Y\n' +
    'A Y\n' +
    'C Z\n' +
    'B Z\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'C Z\n' +
    'A Y\n' +
    'C X\n' +
    'A Y\n' +
    'C Z\n' +
    'A Y\n' +
    'B Y\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'B Y\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'B Y\n' +
    'C X\n' +
    'B Y\n' +
    'C X\n' +
    'B Y\n' +
    'A Y\n' +
    'C X\n' +
    'A X\n' +
    'A X\n' +
    'B X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'B Y\n' +
    'A Y\n' +
    'C X\n' +
    'B Y\n' +
    'B X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'B X\n' +
    'A X\n' +
    'C X\n' +
    'C X\n' +
    'B Y\n' +
    'C Z\n' +
    'B X\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'A X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'A Y\n' +
    'A Y\n' +
    'C Z\n' +
    'C X\n' +
    'A X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'B X\n' +
    'A Z\n' +
    'A Y\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'B Y\n' +
    'A X\n' +
    'C X\n' +
    'A Y\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'A Y\n' +
    'C X\n' +
    'A X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'A Y\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'B X\n' +
    'A Z\n' +
    'C X\n' +
    'B Y\n' +
    'B X\n' +
    'C X\n' +
    'B Y\n' +
    'A Z\n' +
    'A X\n' +
    'C X\n' +
    'A Y\n' +
    'A X\n' +
    'A Z\n' +
    'B Y\n' +
    'A X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'A X\n' +
    'A Z\n' +
    'A Z\n' +
    'B Y\n' +
    'A Z\n' +
    'A X\n' +
    'A Z\n' +
    'C X\n' +
    'B X\n' +
    'A Y\n' +
    'A X\n' +
    'A Y\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'B X\n' +
    'A Y\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'C Y\n' +
    'A Z\n' +
    'A Z\n' +
    'A Z\n' +
    'A Y\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'A Z\n' +
    'B Y\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'A Y\n' +
    'A Z\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'A X\n' +
    'A Z\n' +
    'A Z\n' +
    'B Y\n' +
    'B X\n' +
    'A Z\n' +
    'A X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'A X\n' +
    'A Z\n' +
    'C X\n' +
    'A X\n' +
    'C X\n' +
    'A Z\n' +
    'A Y\n' +
    'C X\n' +
    'B Y\n' +
    'B Y\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A X\n' +
    'A X\n' +
    'A Y\n' +
    'A Z\n' +
    'A X\n' +
    'C X\n' +
    'A X\n' +
    'A Z\n' +
    'B Y\n' +
    'A X\n' +
    'A X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'A X\n' +
    'A X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'C Z\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'A X\n' +
    'C X\n' +
    'B Y\n' +
    'C X\n' +
    'A X\n' +
    'A X\n' +
    'A Y\n' +
    'C X\n' +
    'A Y\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'C Z\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'B X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Y\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'A Y\n' +
    'C X\n' +
    'C Z\n' +
    'C X\n' +
    'C X\n' +
    'B X\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'B X\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'B X\n' +
    'B Y\n' +
    'B Y\n' +
    'C X\n' +
    'C X\n' +
    'C Y\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'A X\n' +
    'A X\n' +
    'A X\n' +
    'A X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'A X\n' +
    'C X\n' +
    'C X\n' +
    'B Y\n' +
    'B Y\n' +
    'A Z\n' +
    'C X\n' +
    'A X\n' +
    'A Z\n' +
    'A Z\n' +
    'B Y\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'B X\n' +
    'C X\n' +
    'A Y\n' +
    'C X\n' +
    'C X\n' +
    'A X\n' +
    'B Y\n' +
    'B Y\n' +
    'C Z\n' +
    'C X\n' +
    'C X\n' +
    'B Y\n' +
    'A X\n' +
    'C X\n' +
    'C X\n' +
    'A X\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'B Y\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'A X\n' +
    'A X\n' +
    'C X\n' +
    'C Z\n' +
    'C X\n' +
    'A Z\n' +
    'B X\n' +
    'C X\n' +
    'B Y\n' +
    'A Y\n' +
    'B X\n' +
    'A Z\n' +
    'A Z\n' +
    'A X\n' +
    'A Z\n' +
    'A Y\n' +
    'A Z\n' +
    'A X\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'B Y\n' +
    'A Z\n' +
    'B X\n' +
    'B Y\n' +
    'A Z\n' +
    'C X\n' +
    'C Y\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'A X\n' +
    'A Z\n' +
    'A X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A X\n' +
    'B X\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'A X\n' +
    'A X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'A X\n' +
    'A Z\n' +
    'C X\n' +
    'A X\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'A X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Y\n' +
    'C X\n' +
    'C X\n' +
    'B Y\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'A X\n' +
    'C X\n' +
    'A X\n' +
    'C X\n' +
    'A Z\n' +
    'B X\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'A Y\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'B X\n' +
    'B X\n' +
    'B Y\n' +
    'A Y\n' +
    'A Y\n' +
    'A Z\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'B Y\n' +
    'C X\n' +
    'B Z\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'B X\n' +
    'A Y\n' +
    'C X\n' +
    'A X\n' +
    'A Z\n' +
    'B Y\n' +
    'A X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'A X\n' +
    'A Z\n' +
    'A X\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'A X\n' +
    'C X\n' +
    'B X\n' +
    'C Z\n' +
    'A X\n' +
    'B X\n' +
    'A Y\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'B X\n' +
    'B Y\n' +
    'B Y\n' +
    'C X\n' +
    'A Z\n' +
    'A X\n' +
    'C X\n' +
    'C X\n' +
    'B Z\n' +
    'B X\n' +
    'B Y\n' +
    'A Z\n' +
    'B Y\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'A X\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'C Y\n' +
    'B X\n' +
    'C X\n' +
    'A X\n' +
    'C X\n' +
    'A X\n' +
    'A Z\n' +
    'C Z\n' +
    'A Z\n' +
    'C X\n' +
    'A Y\n' +
    'C X\n' +
    'C X\n' +
    'B Y\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'C Y\n' +
    'C X\n' +
    'A X\n' +
    'A Z\n' +
    'A X\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'B Y\n' +
    'B X\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'A X\n' +
    'C X\n' +
    'C Y\n' +
    'A Z\n' +
    'A Y\n' +
    'C Z\n' +
    'C X\n' +
    'C Z\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'A Y\n' +
    'A X\n' +
    'B Y\n' +
    'C X\n' +
    'A Y\n' +
    'C X\n' +
    'A Y\n' +
    'C X\n' +
    'A Z\n' +
    'B X\n' +
    'A Y\n' +
    'C X\n' +
    'B X\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'A Y\n' +
    'A Z\n' +
    'A X\n' +
    'B Y\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'A X\n' +
    'C X\n' +
    'A Y\n' +
    'A Y\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'C Y\n' +
    'C X\n' +
    'C X\n' +
    'A X\n' +
    'A Z\n' +
    'A X\n' +
    'A X\n' +
    'C X\n' +
    'A X\n' +
    'A Z\n' +
    'C X\n' +
    'A Y\n' +
    'A Y\n' +
    'C X\n' +
    'B Y\n' +
    'A Y\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'A X\n' +
    'C X\n' +
    'A Y\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Y\n' +
    'A Z\n' +
    'B Y\n' +
    'A X\n' +
    'A Y\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'B X\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'B X\n' +
    'A Z\n' +
    'A X\n' +
    'C X\n' +
    'A X\n' +
    'C X\n' +
    'B Y\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'B X\n' +
    'A Z\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'C Y\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'B X\n' +
    'A X\n' +
    'A Z\n' +
    'C X\n' +
    'B Z\n' +
    'C X\n' +
    'C X\n' +
    'A X\n' +
    'A Y\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'B Y\n' +
    'A Z\n' +
    'C X\n' +
    'A X\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'B Y\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'A Y\n' +
    'A X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'A X\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'A X\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'C Z\n' +
    'A X\n' +
    'C X\n' +
    'C X\n' +
    'A X\n' +
    'A X\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'B Z\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'B X\n' +
    'C X\n' +
    'A Z\n' +
    'B Y\n' +
    'B Y\n' +
    'C X\n' +
    'A X\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'C Y\n' +
    'B Y\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'C Z\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'A Y\n' +
    'C X\n' +
    'A Y\n' +
    'B X\n' +
    'C Z\n' +
    'C X\n' +
    'A Y\n' +
    'C X\n' +
    'B Y\n' +
    'C X\n' +
    'C X\n' +
    'C Z\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'B Z\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'C Y\n' +
    'C X\n' +
    'B Y\n' +
    'A X\n' +
    'A Z\n' +
    'C X\n' +
    'B Y\n' +
    'A Z\n' +
    'B Y\n' +
    'C X\n' +
    'C Y\n' +
    'C Z\n' +
    'A X\n' +
    'A Z\n' +
    'A X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'B Y\n' +
    'B Y\n' +
    'A Y\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A X\n' +
    'C X\n' +
    'B Y\n' +
    'A Z\n' +
    'B Y\n' +
    'C X\n' +
    'C X\n' +
    'B Y\n' +
    'C X\n' +
    'B Y\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'B Z\n' +
    'A X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'A Y\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'A Y\n' +
    'C X\n' +
    'A X\n' +
    'C Y\n' +
    'A Y\n' +
    'A Y\n' +
    'C X\n' +
    'C X\n' +
    'A X\n' +
    'A Y\n' +
    'C X\n' +
    'B Y\n' +
    'A Z\n' +
    'B Y\n' +
    'C X\n' +
    'B X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'B Z\n' +
    'A Y\n' +
    'C X\n' +
    'B Y\n' +
    'C X\n' +
    'A X\n' +
    'C X\n' +
    'C X\n' +
    'B X\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A X\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'C Z\n' +
    'B X\n' +
    'C Z\n' +
    'C X\n' +
    'B X\n' +
    'C X\n' +
    'A Z\n' +
    'B Y\n' +
    'A Z\n' +
    'C Z\n' +
    'C X\n' +
    'B X\n' +
    'A X\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'A Z\n' +
    'A X\n' +
    'C X\n' +
    'C X\n' +
    'A Y\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'B Y\n' +
    'C X\n' +
    'C Z\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A X\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'A Y\n' +
    'A Y\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'B X\n' +
    'C X\n' +
    'B X\n' +
    'B Y\n' +
    'A Z\n' +
    'C X\n' +
    'B Y\n' +
    'A Y\n' +
    'C Z\n' +
    'A Z\n' +
    'A X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'C Z\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'B Y\n' +
    'A Z\n' +
    'B X\n' +
    'A Z\n' +
    'A Z\n' +
    'B X\n' +
    'A X\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'A Y\n' +
    'C X\n' +
    'A Z\n' +
    'B Y\n' +
    'C Y\n' +
    'A Z\n' +
    'C Y\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'A X\n' +
    'C X\n' +
    'A X\n' +
    'A Z\n' +
    'B Y\n' +
    'B Y\n' +
    'C X\n' +
    'B Y\n' +
    'C Z\n' +
    'C X\n' +
    'C X\n' +
    'B Y\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A X\n' +
    'A Z\n' +
    'B Y\n' +
    'A Y\n' +
    'C X\n' +
    'C X\n' +
    'C Z\n' +
    'C X\n' +
    'A X\n' +
    'C X\n' +
    'A Z\n' +
    'B Y\n' +
    'A Z\n' +
    'B X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'A Y\n' +
    'A Y\n' +
    'C X\n' +
    'B X\n' +
    'C X\n' +
    'B X\n' +
    'A Y\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'A X\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'B X\n' +
    'B X\n' +
    'A Z\n' +
    'C X\n' +
    'B Y\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'A X\n' +
    'C X\n' +
    'B Y\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A X\n' +
    'A X\n' +
    'B Y\n' +
    'A Y\n' +
    'A X\n' +
    'C X\n' +
    'A Z\n' +
    'B X\n' +
    'A Z\n' +
    'B Y\n' +
    'C X\n' +
    'B Y\n' +
    'A Y\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Y\n' +
    'A Z\n' +
    'A Z\n' +
    'A X\n' +
    'A Z\n' +
    'A X\n' +
    'C X\n' +
    'A Z\n' +
    'A Y\n' +
    'A Z\n' +
    'A Z\n' +
    'A Z\n' +
    'A X\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'B Y\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'C Y\n' +
    'A Z\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'B X\n' +
    'A X\n' +
    'A Z\n' +
    'A Y\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'A Y\n' +
    'B Y\n' +
    'C X\n' +
    'A X\n' +
    'A Z\n' +
    'A Z\n' +
    'C Y\n' +
    'A X\n' +
    'B Y\n' +
    'B Y\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'A Z\n' +
    'A Z\n' +
    'A Z\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'B Y\n' +
    'C X\n' +
    'C X\n' +
    'A Y\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'A X\n' +
    'C X\n' +
    'A X\n' +
    'C X\n' +
    'C X\n' +
    'B X\n' +
    'C X\n' +
    'B X\n' +
    'C X\n' +
    'C X\n' +
    'A Y\n' +
    'A X\n' +
    'A Z\n' +
    'C X\n' +
    'A X\n' +
    'A Y\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'B Y\n' +
    'A Z\n' +
    'A Y\n' +
    'A Z\n' +
    'C X\n' +
    'A Y\n' +
    'B X\n' +
    'C X\n' +
    'A X\n' +
    'A Y\n' +
    'A Y\n' +
    'A Z\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'A X\n' +
    'A Z\n' +
    'C X\n' +
    'B X\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'A X\n' +
    'A Z\n' +
    'A Z\n' +
    'B Y\n' +
    'A Z\n' +
    'A X\n' +
    'A Z\n' +
    'A Z\n' +
    'A Z\n' +
    'A X\n' +
    'B Y\n' +
    'A X\n' +
    'A Z\n' +
    'C X\n' +
    'B X\n' +
    'A Z\n' +
    'A Z\n' +
    'A Y\n' +
    'B Y\n' +
    'A Y\n' +
    'B Y\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'B Y\n' +
    'A Z\n' +
    'A X\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'A X\n' +
    'C X\n' +
    'B Y\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'C Z\n' +
    'A Y\n' +
    'C X\n' +
    'A Y\n' +
    'A Y\n' +
    'A Y\n' +
    'A Z\n' +
    'A X\n' +
    'A Z\n' +
    'A X\n' +
    'A Z\n' +
    'B Y\n' +
    'C X\n' +
    'A Z\n' +
    'A Y\n' +
    'C X\n' +
    'B Y\n' +
    'A Z\n' +
    'B Y\n' +
    'C X\n' +
    'B X\n' +
    'B Y\n' +
    'C X\n' +
    'A Z\n' +
    'B X\n' +
    'C X\n' +
    'B Y\n' +
    'B Y\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'B X\n' +
    'A X\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'B X\n' +
    'A Z\n' +
    'C Y\n' +
    'C X\n' +
    'A Z\n' +
    'A X\n' +
    'B Y\n' +
    'B Y\n' +
    'C Y\n' +
    'B Y\n' +
    'A Y\n' +
    'C X\n' +
    'A X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Y\n' +
    'A Z\n' +
    'B Y\n' +
    'A Z\n' +
    'A Y\n' +
    'C X\n' +
    'A Y\n' +
    'A Y\n' +
    'A Y\n' +
    'C X\n' +
    'B X\n' +
    'B X\n' +
    'C X\n' +
    'B X\n' +
    'C X\n' +
    'C X\n' +
    'A X\n' +
    'A X\n' +
    'A X\n' +
    'C X\n' +
    'C X\n' +
    'C Y\n' +
    'A Y\n' +
    'A Z\n' +
    'C X\n' +
    'B Y\n' +
    'C X\n' +
    'A X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'B X\n' +
    'C X\n' +
    'C Z\n' +
    'A Z\n' +
    'C Y\n' +
    'B Y\n' +
    'A Y\n' +
    'A Z\n' +
    'A Z\n' +
    'A X\n' +
    'A Y\n' +
    'C X\n' +
    'C Y\n' +
    'C X\n' +
    'C X\n' +
    'A X\n' +
    'A Y\n' +
    'A Z\n' +
    'C X\n' +
    'B X\n' +
    'B Y\n' +
    'B Y\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'B Y\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'A Z\n' +
    'A X\n' +
    'A Y\n' +
    'A Z\n' +
    'C Z\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'B Y\n' +
    'A X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'A X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'A X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Y\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'B Z\n' +
    'A Z\n' +
    'A Y\n' +
    'C X\n' +
    'B X\n' +
    'C X\n' +
    'C X\n' +
    'C Z\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A X\n' +
    'A Z\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'B Y\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'A Y\n' +
    'C X\n' +
    'B Y\n' +
    'A Z\n' +
    'C X\n' +
    'B X\n' +
    'C X\n' +
    'A X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'A Z\n' +
    'B Z\n' +
    'C X\n' +
    'A Z\n' +
    'A X\n' +
    'C X\n' +
    'B X\n' +
    'A X\n' +
    'A Y\n' +
    'B Y\n' +
    'B Y\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'A X\n' +
    'B Y\n' +
    'B Y\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'A Y\n' +
    'C X\n' +
    'A Y\n' +
    'A Z\n' +
    'A Y\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'B Y\n' +
    'A X\n' +
    'A Z\n' +
    'C X\n' +
    'A X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'B X\n' +
    'B X\n' +
    'A Z\n' +
    'C X\n' +
    'A Y\n' +
    'A Z\n' +
    'C X\n' +
    'A X\n' +
    'A X\n' +
    'A Z\n' +
    'A Y\n' +
    'C X\n' +
    'A Z\n' +
    'B Z\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'B X\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'A X\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'A X\n' +
    'A Z\n' +
    'A Z\n' +
    'C Z\n' +
    'C X\n' +
    'C X\n' +
    'B Y\n' +
    'B Y\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'B X\n' +
    'A X\n' +
    'C X\n' +
    'A X\n' +
    'B Y\n' +
    'C X\n' +
    'B Y\n' +
    'A Z\n' +
    'A Z\n' +
    'A Y\n' +
    'A Z\n' +
    'B X\n' +
    'A X\n' +
    'C X\n' +
    'B Y\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'A X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'B Y\n' +
    'C X\n' +
    'A Z\n' +
    'B Y\n' +
    'A Z\n' +
    'A Z\n' +
    'A X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'B Y\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A X\n' +
    'B Y\n' +
    'C X\n' +
    'A X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'B X\n' +
    'B X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'B X\n' +
    'C X\n' +
    'A X\n' +
    'C X\n' +
    'B Y\n' +
    'A Y\n' +
    'C Z\n' +
    'C X\n' +
    'A Z\n' +
    'C Z\n' +
    'B Y\n' +
    'B Y\n' +
    'A Z\n' +
    'C Z\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A X\n' +
    'C X\n' +
    'A Z\n' +
    'B X\n' +
    'A Z\n' +
    'B Y\n' +
    'A Z\n' +
    'B X\n' +
    'A X\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'B X\n' +
    'C X\n' +
    'A Z\n' +
    'B Y\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'A X\n' +
    'A Z\n' +
    'A X\n' +
    'A X\n' +
    'C X\n' +
    'B X\n' +
    'C X\n' +
    'C X\n' +
    'B Y\n' +
    'C X\n' +
    'C X\n' +
    'A X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'B Y\n' +
    'C X\n' +
    'C Z\n' +
    'C X\n' +
    'B Y\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'A Y\n' +
    'A X\n' +
    'C X\n' +
    'C X\n' +
    'B Y\n' +
    'C Z\n' +
    'C X\n' +
    'A Y\n' +
    'B Y\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'B X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'B Y\n' +
    'A X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'B Y\n' +
    'C X\n' +
    'A Y\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'B Y\n' +
    'C X\n' +
    'C Y\n' +
    'A Y\n' +
    'C X\n' +
    'B Y\n' +
    'A Z\n' +
    'B X\n' +
    'C X\n' +
    'C X\n' +
    'A X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A X\n' +
    'A X\n' +
    'A Z\n' +
    'C X\n' +
    'B Z\n' +
    'C X\n' +
    'A Y\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'A X\n' +
    'A Z\n' +
    'A Z\n' +
    'A Z\n' +
    'A Y\n' +
    'A X\n' +
    'A Z\n' +
    'C X\n' +
    'B Y\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'C Z\n' +
    'B X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'A X\n' +
    'B X\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'A Z\n' +
    'C Z\n' +
    'C X\n' +
    'B Y\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'B Y\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A X\n' +
    'C Z\n' +
    'B Y\n' +
    'A X\n' +
    'A X\n' +
    'B X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'B X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'C Y\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'A Z\n' +
    'A Y\n' +
    'A X\n' +
    'A X\n' +
    'C X\n' +
    'A Z\n' +
    'B X\n' +
    'A Z\n' +
    'C X\n' +
    'B X\n' +
    'C X\n' +
    'A Y\n' +
    'A X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'B X\n' +
    'B X\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'B X\n' +
    'A Z\n' +
    'A Y\n' +
    'A X\n' +
    'A Y\n' +
    'C X\n' +
    'A Z\n' +
    'B Y\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'A Y\n' +
    'B X\n' +
    'A Z\n' +
    'C X\n' +
    'A X\n' +
    'A Z\n' +
    'A Z\n' +
    'A Z\n' +
    'A X\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'B X\n' +
    'A Y\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'B X\n' +
    'B Y\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'B Y\n' +
    'B Y\n' +
    'C X\n' +
    'B X\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'B Y\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'A X\n' +
    'C X\n' +
    'C X\n' +
    'A X\n' +
    'A Z\n' +
    'C X\n' +
    'A X\n' +
    'C X\n' +
    'C X\n' +
    'A X\n' +
    'C X\n' +
    'A X\n' +
    'A Y\n' +
    'A Z\n' +
    'A Y\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'B Z\n' +
    'A Y\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'A X\n' +
    'C X\n' +
    'C Y\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'B X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'C Z\n' +
    'C X\n' +
    'A X\n' +
    'A Y\n' +
    'B Y\n' +
    'A Z\n' +
    'A X\n' +
    'B X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Y\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'A X\n' +
    'C X\n' +
    'C Z\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'A Y\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'C Y\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'A X\n' +
    'C X\n' +
    'B X\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'A Y\n' +
    'C Y\n' +
    'A Z\n' +
    'A Z\n' +
    'B X\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'B Y\n' +
    'A Z\n' +
    'B Y\n' +
    'C X\n' +
    'B X\n' +
    'A X\n' +
    'C X\n' +
    'A Z\n' +
    'A Y\n' +
    'C X\n' +
    'A Z\n' +
    'C Z\n' +
    'A X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'A Y\n' +
    'C X\n' +
    'C X\n' +
    'A Y\n' +
    'C X\n' +
    'B X\n' +
    'C X\n' +
    'C X\n' +
    'B Y\n' +
    'A X\n' +
    'C X\n' +
    'A Y\n' +
    'B Y\n' +
    'C X\n' +
    'A X\n' +
    'A Z\n' +
    'C Z\n' +
    'A X\n' +
    'C X\n' +
    'C X\n' +
    'B X\n' +
    'A Z\n' +
    'B Z\n' +
    'A Z\n' +
    'A X\n' +
    'A Y\n' +
    'C X\n' +
    'A X\n' +
    'B X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'B X\n' +
    'C X\n' +
    'A Y\n' +
    'A Z\n' +
    'A X\n' +
    'A X\n' +
    'C X\n' +
    'A Y\n' +
    'C X\n' +
    'C X\n' +
    'A Y\n' +
    'C X\n' +
    'B X\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'B X\n' +
    'A Z\n' +
    'B Y\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'A X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'A X\n' +
    'B Y\n' +
    'A Y\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'A X\n' +
    'C X\n' +
    'C X\n' +
    'A Y\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'A Y\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'C Z\n' +
    'A Y\n' +
    'C X\n' +
    'C X\n' +
    'B Z\n' +
    'B Y\n' +
    'B Y\n' +
    'B Y\n' +
    'C Z\n' +
    'B Y\n' +
    'A Z\n' +
    'B X\n' +
    'C X\n' +
    'A Z\n' +
    'A Y\n' +
    'C X\n' +
    'B Y\n' +
    'C X\n' +
    'A X\n' +
    'B X\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'C Y\n' +
    'A Z\n' +
    'B Y\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'B Y\n' +
    'C X\n' +
    'A Z\n' +
    'C Z\n' +
    'A X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'B X\n' +
    'B Y\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'C Z\n' +
    'C X\n' +
    'B X\n' +
    'A X\n' +
    'B Z\n' +
    'A Z\n' +
    'C X\n' +
    'A X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'A X\n' +
    'A Z\n' +
    'C X\n' +
    'A X\n' +
    'C X\n' +
    'C Y\n' +
    'C X\n' +
    'A Z\n' +
    'B X\n' +
    'A Y\n' +
    'A Z\n' +
    'C Y\n' +
    'A Z\n' +
    'C X\n' +
    'A Y\n' +
    'C X\n' +
    'A X\n' +
    'C X\n' +
    'A X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'A X\n' +
    'A Z\n' +
    'A X\n' +
    'A Y\n' +
    'C Z\n' +
    'C X\n' +
    'A X\n' +
    'A Z\n' +
    'A Z\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'C Z\n' +
    'A X\n' +
    'A Z\n' +
    'B Y\n' +
    'A Z\n' +
    'A Z\n' +
    'B X\n' +
    'B Y\n' +
    'A X\n' +
    'A Y\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'B X\n' +
    'B X\n' +
    'C X\n' +
    'C X\n' +
    'C X\n' +
    'A X\n' +
    'C X\n' +
    'A Z\n' +
    'B X\n' +
    'A Y\n' +
    'B X\n' +
    'C X\n' +
    'A X\n' +
    'C X\n' +
    'A X\n' +
    'A Z\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'B Y\n' +
    'C X\n' +
    'B Y\n' +
    'C X\n' +
    'A Z\n' +
    'A Z\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'B Y\n' +
    'A Y\n' +
    'C Y\n' +
    'A Z\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'C X\n' +
    'A Z\n' +
    'C Z\n' +
    'B X\n' +
    'C X\n' +
    'C X\n' +
    'A Z\n' +
    'B Y\n' +
    'A Y\n' +
    'C X\n' +
    'A X'

const testInput = 'A Z\n' +
    'B Y\n' +
    'A Y\n' +
    'C X\n' +
    'A X'

const shapeValues = {X: 1, Y: 2, Z: 3}

const gameResults = {
    A: {X: 3, Y: 6, Z: 0},
    B: {X: 0, Y: 3, Z: 6},
    C: {X: 6, Y: 0, Z: 3}
}

const gamesArr = input.split('\n');

const gameScore = (game) => {
    const [opponentMove, yourMove] = game.split(' ');
    const relevantGameResults = gameResults[opponentMove];
    const gameScore = relevantGameResults[yourMove];
    const moveScore = shapeValues[yourMove];

    return gameScore + moveScore;
}

const totalSore = gamesArr.map(gameScore).reduce((acc, cur) => acc + +cur, 0);

console.log(totalSore);

const requiredResults = {
    A: {X: 'S', Y: 'R', Z: 'P'},
    B: {X: 'R', Y: 'P', Z: 'S'},
    C: {X: 'P', Y: 'S', Z: 'R'}
}
const anotherMoveValues = {R: 1, P: 2, S: 3};
const anotherGameValues = {X:0,Y:3,Z:6}

const anotherGameScore = (game) => {
    const [opponentMove, gameOutcome] = game.split(' ');
    const yourMove = requiredResults[opponentMove][gameOutcome];
    const gameScore = anotherGameValues[gameOutcome];
    const moveScore = anotherMoveValues[yourMove]

    return gameScore + moveScore;
}

const anotherTotalSore = gamesArr.map(anotherGameScore).reduce((acc, cur) => acc + +cur, 0)

console.log(anotherTotalSore);


